-- Load server configurations
require("servers.lua_ls")
require("servers.pyright")
require("servers.vtsls")
require("servers.gopls")
require("servers.bashls")
require("servers.dockerls")
require("servers.clangd")
require("servers.jsonls")
require("servers.emmet_ls")
require("servers.tailwindcss")
require("servers.yamlls")

-- Enable all servers
vim.lsp.enable("lua_ls")
vim.lsp.enable("basedpyright")
vim.lsp.enable("vtsls")
vim.lsp.enable("gopls")
vim.lsp.enable("bashls")
vim.lsp.enable("dockerls")
vim.lsp.enable("docker_compose_language_service")
vim.lsp.enable("clangd")
vim.lsp.enable("jsonls")
vim.lsp.enable("emmet_ls")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("yamlls")
